name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configurar Git
        run: |
          git config user.name "oleojake"
          git config user.email "oleojake@gmail.com"

      - name: Deploy to GitHub Pages
        run: npm run deploy -- -r https://github.com/oleojake/cloud-2.git
